<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="N700278" name="SitTest.US470LoadProFromOtherTrailer" tests="4" failures="4" timestamp="20 Jan 2016 18:36:31 GMT" time="179.285" errors="0">
  <testcase name="NoProTrailerPullProFromTrailerInSameTerminal" time="41.057" classname="SitTest.US470LoadProFromOtherTrailer">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Waybill table Destination_facility_cd is wrong 0135824749	Waybill table Destination_facility_cd is wrong 0135824749 expected [112] but found [null], 
	waybill table 9  Wed Oct 21 04:00:00 UTC 2015  Wed Jan 20 18:35:13 UTC 2016     0135824749 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Waybill table Destination_facility_cd is wrong 0135824749	Waybill table Destination_facility_cd is wrong 0135824749 expected [112] but found [null], 
	waybill table 9  Wed Oct 21 04:00:00 UTC 2015  Wed Jan 20 18:35:13 UTC 2016     0135824749 expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:48)
	at SitTest.US470LoadProFromOtherTrailer.NoProTrailerPullProFromTrailerInSameTerminal(US470LoadProFromOtherTrailer.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- NoProTrailerPullProFromTrailerInSameTerminal -->
  <testcase name="NoProTrailerPullProFromTrailerInOtherTerminal" time="53.902" classname="SitTest.US470LoadProFromOtherTrailer">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Waybill table Destination_facility_cd is wrong 0135824749	Waybill table Destination_facility_cd is wrong 0135824749 expected [841] but found [null], 
	waybill table 9  Wed Oct 21 04:00:00 UTC 2015  Wed Jan 20 18:33:30 UTC 2016     0135824749 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Waybill table Destination_facility_cd is wrong 0135824749	Waybill table Destination_facility_cd is wrong 0135824749 expected [841] but found [null], 
	waybill table 9  Wed Oct 21 04:00:00 UTC 2015  Wed Jan 20 18:33:30 UTC 2016     0135824749 expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:48)
	at SitTest.US470LoadProFromOtherTrailer.NoProTrailerPullProFromTrailerInOtherTerminal(US470LoadProFromOtherTrailer.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- NoProTrailerPullProFromTrailerInOtherTerminal -->
  <testcase name="WithProTrailerPullProFromTrailerInSameTerminal" time="43.306" classname="SitTest.US470LoadProFromOtherTrailer">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Waybill table Destination_facility_cd is wrong 0135824749	Waybill table Destination_facility_cd is wrong 0135824749 expected [841] but found [null], 
	waybill table 9  Wed Oct 21 04:00:00 UTC 2015  Wed Jan 20 18:36:05 UTC 2016     0135824749 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Waybill table Destination_facility_cd is wrong 0135824749	Waybill table Destination_facility_cd is wrong 0135824749 expected [841] but found [null], 
	waybill table 9  Wed Oct 21 04:00:00 UTC 2015  Wed Jan 20 18:36:05 UTC 2016     0135824749 expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:48)
	at SitTest.US470LoadProFromOtherTrailer.WithProTrailerPullProFromTrailerInSameTerminal(US470LoadProFromOtherTrailer.java:398)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- WithProTrailerPullProFromTrailerInSameTerminal -->
  <testcase name="WithProTrailerPullProFromTrailerInOtherTerminal" time="41.020" classname="SitTest.US470LoadProFromOtherTrailer">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Waybill table Destination_facility_cd is wrong 1084440480	Waybill table Destination_facility_cd is wrong 1084440480 expected [841] but found [null], 
	waybill table 9  Sat Oct 31 04:00:00 UTC 2015  Wed Jan 20 18:34:20 UTC 2016     1084440480 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Waybill table Destination_facility_cd is wrong 1084440480	Waybill table Destination_facility_cd is wrong 1084440480 expected [841] but found [null], 
	waybill table 9  Sat Oct 31 04:00:00 UTC 2015  Wed Jan 20 18:34:20 UTC 2016     1084440480 expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:48)
	at SitTest.US470LoadProFromOtherTrailer.WithProTrailerPullProFromTrailerInOtherTerminal(US470LoadProFromOtherTrailer.java:216)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- WithProTrailerPullProFromTrailerInOtherTerminal -->
</testsuite> <!-- SitTest.US470LoadProFromOtherTrailer -->
